 INSERT INTO `compagnies_aeriennes` (`ID_compagnie`, `Nom_compagnie`, `Code_compagnie`, `Pays_origine`, `Site_web`) VALUES
(1, 'Air Asia X', 'IDX', 'Indonesia', 'Y'),
(2, 'Alghanim', 'KYA', 'United States', 'Y'),
(3, 'Norwegian Air International', 'IBK', 'Norway', 'Y'),
(4, 'Boliviana de Aviacion', 'BOV', 'Bolivia', 'Y'),
(5, 'AtlasGlobal Ukraine', 'UJX', 'Ukraine', 'Y'),
(6, 'Pouya Air', 'PYA', 'Iran', 'Y'),
(7, 'Mann Yadanarpon Airlines', 'MYP', 'Burma', 'Y'),
(8, 'BA101', '710', 'United Kingdom', 'Y'),
(9, 'Fly Africa Zimbabwe', 'FZW', 'Zimbabwe', 'Y'),
(10, 'Jet Suite', 'RSP', 'United States', 'Y'),
(11, 'FTI Fluggesellschaft', 'FTI', 'Germany', 'N'),
(12, 'Go2Sky', 'RLX', 'Slovakia', 'Y'),
(13, 'Tomsk-Avia', 'TKS', 'Russia', 'Y'),
(14, 'Simrik Airlines', 'RMK', 'Nepal', 'Y'),
(15, 'Russkie Krylya', 'KRY', 'Russia', 'Y'),
(16, 'FLYJET', 'FYJ', 'Poland', 'Y'),
(17, 'Comfort Express Virtual Charters Albany', 'EVC', 'United States', 'Y'),
(18, 'Golden Myanmar Airlines', 'GMR', 'Burma', 'Y'),
(19, 'Nurnberger Flugdienst', 'NFD', 'Germany', 'N'),
(20, 'Eastern Atlantic Charters', 'EDI', 'United States', 'N'),
(21, 'Taunus Air Gmbh', 'TAQ', 'Germany', 'N'),
(22, 'Bingo Airways', 'BGY', 'Poland', 'Y'),
(23, 'Flybe Finland Oy', 'FCM', 'Finland', 'Y'),
(24, 'Rotana Jet', 'RJD', 'United Arab Emirates', 'Y'),
(25, 'East Horizon', 'EHN', 'Afghanistan', 'Y'),
(26, 'Executive AirShare', 'XSR', 'United States', 'Y'),
(27, 'Air Engiadina-BRN', 'RQX', 'Switzerland', 'N'),
(28, 'Malaysia Wings', 'MWI', 'Malaysia', 'Y'),
(29, 'Medallion Air', 'MDP', 'Romania', 'Y'),
(30, 'Direct Aero Services', 'DSV', 'Romania', 'Y'),
(31, 'YES Airways', 'YEP', 'Poland', 'Y'),
(32, 'AlbaStar', 'LAV', 'Spain', 'Y'),
(33, 'Air Bucharest', 'BUR', 'Romania', 'Y'),
(34, 'Holidays Czech Airlines', 'HCC', 'Czech Republic', 'Y'),
(35, 'Air Cudlua', 'CUD', 'United Kingdom', 'Y'),
(36, 'Kan Air', 'KND', 'Thailand', 'Y'),
(37, 'Compania de Aviacion Faucett', 'CFP', 'Peru', 'N'),
(38, 'OCEAN AIR CARGO', 'IXO', 'India', 'Y'),
(39, 'SUR Lineas Aereas', 'SZZ', 'Argentina', 'Y'),
(40, 'CBM America', 'XBM', 'United States', 'Y'),
(41, 'Finlandian', 'FN1', 'Finland', 'Y'),
(42, 'Zapolyarie Airlines', 'PZY', 'Russia', 'Y'),
(43, 'Korea Express Air', 'KEA', 'South Korea', 'Y'),
(44, 'Jupiter Airlines', 'JPU', 'United Arab Emirates', 'Y'),
(45, 'Grand China Air', 'GDC', 'China', 'Y'),
(46, 'Flugfelag Vestmannaeyja', 'FVM', 'Iceland', 'Y'),
(47, 'Norlandair', 'FNA', 'Iceland', 'Y'),
(48, 'Sevenair', 'SEN', 'Tunisia', 'Y'),
(49, 'Wind Rose Aviation', 'WRC', 'Ukraine', 'Y'),
(50, 'Air Italy Egypt', 'EUD', 'Egypt', 'Y'),
(51, 'EgyptAir Express', 'MSE', 'Egypt', 'Y'),
(52, 'Air 26', 'DCD', 'Angola', 'Y'),
(53, 'Air Century', 'CEY', 'Dominican Republic', 'Y'),
(54, 'Southern Air Charter', 'SOA', 'Bahamas', 'Y'),
(55, 'Enerjet', 'ENJ', 'Canada', 'Y'),
(56, 'LIO Flugmennt', 'LIO', 'Iceland', 'N'),
(57, 'Hellenic Star Airways', 'HST', 'Greece', 'N'),
(58, 'Inter European Airways', 'IEA', 'United Kingdom', 'N'),
(59, 'Dan-Air London', 'DAN', 'United Kingdom', 'N'),
(60, 'Zorex', 'ORZ', 'Spain', 'N'),
(61, 'Zhez Air', 'KZH', 'Kazakhstan', 'N'),
(62, 'Zhejiang Airlines', 'CJG', 'China', 'N'),
(63, 'Zephyr Express', 'RZR', 'United States', 'N'),
(64, 'Zenith Air', 'AZR', 'South Africa', 'N'),
(65, 'Zantop International Airlines', 'ZAN', 'United States', 'N'),
(66, 'Zanair', 'TAN', 'Tanzania', 'Y'),
(67, 'Zaire Aero Service', 'ZAI', 'Democratic Republic of Congo', 'N'),
(68, 'Zagros Airlines', 'IZG', 'Iran', 'N'),
(69, 'Z-Avia', 'RZV', 'Armenia', 'N'),
(70, 'Yuzhmashavia', 'UMK', 'Ukraine', 'Y'),
(71, 'Yuzhnaya Aircompany', 'UGN', 'Kazakhstan', 'N'),
(72, 'Yellow Wings Air Services', 'ELW', 'Kenya', 'N'),
(73, 'Yak-Service', 'AKY', 'Russia', 'N'),
(74, 'Xerox Corporation', 'XER', 'United States', 'N'),
(75, 'Xclusive Jet Charter Limited', 'XJC', 'United Kingdom', 'N'),
(76, 'XP Internation', 'XPS', 'Netherlands', 'N'),
(77, 'Worldwide Jet Charter', 'WWI', 'United States', 'N'),
(78, 'Woodgate Executive Air Charter', 'CWY', 'United Kingdom', 'N'),
(79, 'Wisman Aviation', 'WSM', 'United States', 'N'),
(80, 'Winlink', 'WIN', 'Saint Lucia', 'N'),
(81, 'Wings of Lebanon Aviation', 'WLB', 'Lebanon', 'N'),
(82, 'Wings Aviation', 'WOL', 'Guyana', 'N'),
(83, 'Wings Airways', 'WAW', 'United States', 'N'),
(84, 'Wings Air Transport', 'WAT', 'Sudan', 'N'),
(85, 'Windrose Air', 'QGA', 'Germany', 'N'),
(86, 'Wind Spirit Air', 'WSI', 'United States', 'N'),
(87, 'Winair', 'WNA', 'United States', 'N'),
(88, 'Williams Air', 'WLS', 'United States', 'N'),
(89, 'Wiking Helikopter Service', 'WHS', 'Germany', 'N'),
(90, 'Wiggins Airways', 'WIG', 'United States', 'N'),
(91, 'Whyalla Airlines', 'WWL', 'Australia', 'N'),
(92, 'White Eagle Aviation', 'WEA', 'Poland', 'N'),
(93, 'White', 'WHT', 'Portugal', 'N'),
(94, 'Westland Helicopters', 'WHE', 'United Kingdom', 'N'),
(95, 'Western Aviators', 'WTV', 'United States', 'N'),
(96, 'Western Arctic Air', 'WAL', 'Canada', 'N'),
(97, 'Western Air', 'WST', 'Bahamas', 'N'),
(98, 'Westair Aviation', 'WAA', 'Namibia', 'N'),
(99, 'West Coast Airlines', 'WCG', 'Ghana', 'N'),
(100, 'West Air Luxembourg', 'WLX', 'Luxembourg', 'N'),
(101, 'West African Airlines', 'WSF', 'Benin', 'N'),
(102, 'Welch Aviation', 'TDB', 'United States', 'N'),
(103, 'Weasua Air Transport Company', 'WTC', 'Liberia', 'N'),
(104, 'Warbelow\'s Air Ventures', 'WAV', 'United States', 'N'),
(105, 'Wapiti Aviation', 'WPT', 'Canada', 'N'),
(106, 'Walter I Linkoping', 'GOT', 'Sweden', 'N'),
(107, 'Walsten Air Services', 'WAS', 'Canada', 'N'),
(108, 'Walmart Aviation', 'CGG', 'United States', 'N'),
(109, 'WSI Corporation', 'XWS', 'United States', 'N'),
(110, 'WRA Inc', 'WRR', 'United States', 'N'),
(111, 'Volga Aviaexpress', 'WLG', 'Russia', 'N'),
(112, 'Vuelos Internos Privados VIP', 'VUR', 'Ecuador', 'N'),
(113, 'Vointeh', 'VTV', 'Bulgaria', 'N'),
(114, 'Victor Tagle Larrain', 'VTL', 'Chile', 'N'),
(115, 'Voronezh Aircraft Manufacturing Society', 'VSO', 'Russia', 'N'),
(116, 'Vickers Limited', 'VSB', 'United Kingdom', 'N'),
(117, 'Voar Lda', 'VRL', 'Angola', 'N'),
(118, 'Volare Airlines', 'VRE', 'Ukraine', 'N'),
(119, 'Vertair', 'VRA', 'United Kingdom', 'N'),
(120, 'VIP-Avia', 'VPV', 'Georgia', 'N'),
(121, 'VIP Air', 'VPA', 'Slovakia', 'N'),
(122, 'Vertical-T Air Company', 'VLT', 'Russia', 'N'),
(123, 'Vistajet', 'VJT', 'Canada', 'N'),
(124, 'Viking Airlines', 'VIK', 'Sweden', 'N'),
(125, 'Vichi', 'VIH', 'Moldova', 'N'),
(126, 'Vega Aviation', 'VIG', 'Sudan', 'N'),
(127, 'VZ Flights', 'VFT', 'Mexico', 'N'),
(128, 'Viscount Air Service', 'VCT', 'United States', 'N'),
(129, 'VIM-Aviaservice', 'MVY', 'Russia', 'N'),
(130, 'Veritair Ltd', 'BTP', 'United Kingdom', 'N'),
(131, 'Vega Air Company', 'WGA', 'Ukraine', 'N'),
(132, 'Vega', 'VAG', 'Kazakhstan', 'N'),
(133, 'Valan Limited', 'VLN', 'Moldova', 'N'),
(134, 'Vacationair', 'VAC', 'Canada', 'N'),
(135, 'Universal Airlines', 'UVG', 'Guyana', 'N'),
(136, 'Universal Airways', 'UVA', 'United States', 'N'),
(137, 'UTAGE', 'UTG', 'Equatorial Guinea', 'N'),
(138, 'US Check Airlines', 'USC', 'United States', 'N'),
(139, 'Uraiavia', 'URV', 'Russia', 'N'),
(140, 'Unsped Paket Servisi', 'UNS', 'Turkey', 'N'),
(141, 'Universal Jet', 'UNJ', 'Spain', 'N'),
(142, 'Ukraine Air Alliance', 'UKL', 'Ukraine', 'N'),
(143, 'Universal Jet Aviation', 'UJT', 'United States', 'N'),
(144, 'Uganda Airlines', 'UGA', 'Uganda', 'N'),
(145, 'UFS', 'UFS', 'United States', 'N'),
(146, 'Ues-Avia Aircompany', 'UES', 'Ukraine', 'N'),
(147, 'United Arab Emirates Air Force', 'UAF', 'United Arab Emirates', 'N'),
(148, 'Ukraine Transavia', 'TRB', 'Ukraine', 'N'),
(149, 'Universal Airlines', 'PNA', 'United States', 'N'),
(150, 'University of North Dakota', 'NDU', 'United States', 'N'),
(151, 'US Marshals Service', 'MSH', 'United States', 'N'),
(152, 'Unijet', 'LEA', 'France', 'N'),
(153, 'University Air Squadron', 'UAJ', 'United Kingdom', 'N'),
(154, 'University Air Squadron', 'UAD', 'United Kingdom', 'N'),
(155, 'United States Department Of Agriculture', 'AGR', 'United States', 'N'),
(156, 'United States Coast Guard Auxiliary', 'CGX', 'United States', 'N'),
(157, 'United Kingdom Royal VIP Flights', 'TQF', 'United Kingdom', 'N'),
(158, 'United Kingdom Civil Aviation Authority', 'SDS', 'United Kingdom', 'N'),
(159, 'United Kingdom Royal VIP Flight', 'KRH', 'United Kingdom', 'N'),
(160, 'United Arabian Airlines', 'UAB', 'Sudan', 'N'),
(161, 'US Army Parachute Team', 'GKA', 'United States', 'N'),
(162, 'United Kingdom Civil Aviation Authority', 'EXM', 'United Kingdom', 'N'),
(163, 'Travel Express Aviation Services', 'XAR', 'Indonesia', 'N'),
(164, 'Taxi de Veracruz', 'VRC', 'Mexico', 'N'),
(165, 'Tag Aviation UK', 'VIP', 'United Kingdom', 'N'),
(166, 'Transaven', 'VEN', 'Venezuela', 'N'),
(167, 'Transarabian Transportation Services', 'UTT', 'Uganda', 'N'),
(168, 'TAPC Aviatrans Aircompany', 'UTM', 'Uzbekistan', 'N'),
(169, 'Trans Asian Airlines', 'SRT', 'Kazakhstan', 'N'),
(170, 'Trans Am Compania', 'RTM', 'Ecuador', 'N'),
(171, 'Tbilisi Aviation University', 'RRY', 'Georgia', 'N'),
(172, 'Tas Aviation', 'RMS', 'United States', 'N'),
(173, 'Trans-Pacific Orient Airways', 'PCW', 'Philippines', 'N'),
(174, 'Transportacion Aerea Del Mar De Cortes', 'MCT', 'Mexico', 'N'),
(175, 'Top Sky International', 'LKW', 'Indonesia', 'N'),
(176, 'The Army Aviation Heritage Foundation', 'LEG', 'United States', 'N'),
(177, 'The Lancair Company', 'LCC', 'United States', 'N'),
(178, 'Transaviabaltika', 'KTB', 'Lithuania', 'N'),
(179, 'Transcontinental Airlines', 'KRA', 'Kazakhstan', 'N'),
(180, 'Trading Air Cargo', 'JCH', 'Mauritania', 'N'),
(181, 'Tango Bravo', 'HTO', 'France', 'N'),
(182, 'TAF Helicopters', 'HET', 'Spain', 'N'),
(183, 'Tradewind Aviation', 'GPD', 'United States', 'N'),
(184, 'Trans-Air-Link', 'GJB', 'United States', 'N'),
(185, 'Transportes Aereos Don Carlos', 'DCL', 'Chile', 'N'),
(186, 'Tashkent Aircraft Production Corporation', 'CTP', 'Uzbekistan', 'N'),
(187, 'Triple Alpha', 'CLU', 'Germany', 'N'),
(188, 'Tiphook PLC', 'BOX', 'United Kingdom', 'N'),
(189, 'Tajikstan', 'TZK', 'Tajikistan', 'N'),
(190, 'Transporte Aereo Ernesto Saenz', 'TZE', 'Mexico', 'N'),
(191, 'Tyrol Air Ambulance', 'TYW', 'Austria', 'N'),
(192, 'Texas Air Charters', 'TXT', 'United States', 'N'),
(193, 'Texas Airlines', 'TXS', 'United States', 'N'),
(194, 'Taxirey', 'TXR', 'Mexico', 'N'),
(195, 'Taxi Aereo Cozatl', 'TXL', 'Mexico', 'N'),
(196, 'Twinjet Aircraft Sales', 'TWJ', 'United Kingdom', 'N'),
(197, 'Transwede Airways', 'TWE', 'Sweden', 'N'),
(198, 'Trabajos Aereos Vascongados', 'TVH', 'Spain', 'N'),
(199, 'Tuna Aero', 'TUZ', 'Sweden', 'N'),
(200, 'Taftan Airlines', 'SBT', 'Iran', 'N'),
(201, 'Tramson Limited', 'TRR', 'Sudan', 'N'),
(202, 'Trans Euro Air', 'TRJ', 'United Kingdom', 'N'),
(203, 'Trans Air Charter', 'TRC', 'United States', 'N'),
(204, 'Transportacion Aerea De Queretaro', 'TQR', 'Mexico', 'N'),
(205, 'Taquan Air Services', 'TQN', 'United States', 'N'),
(206, 'Transportes Aereos De Xalapa', 'TPX', 'Mexico', 'N'),
(207, 'Thai Pacific Airlines Business', 'TPV', 'Thailand', 'N'),
(208, 'Trans American Airlines (Trans Am)', 'TPU', 'Peru', 'N'),
(209, 'Taxis Aereos De Parral', 'TPR', 'Mexico', 'N'),
(210, 'Transpac Express', 'TPP', 'Australia', 'N'),
(211, 'Transportacion Aerea del Norte', 'TPN', 'Mexico', 'N'),
(212, 'Top Speed', 'TPD', 'Austria', 'N'),
(213, 'Twin Town Leasing Company', 'TNY', 'United States', 'N'),
(214, 'Trener Ltd', 'TNX', 'Hungary', 'N'),
(215, 'Transnorthern', 'TNV', 'United States', 'N'),
(216, 'Trans Air-Benin', 'TNB', 'Benin', 'N'),
(217, 'Tranporte Amazonair', 'TMZ', 'Venezuela', 'N'),
(218, 'Transportes Aereos del Mundo Maya', 'TMY', 'Mexico', 'N'),
(219, 'Tramon Air', 'TMX', 'South Africa', 'N'),
(220, 'Temsco Helicopters', 'TMS', 'United States', 'N'),
(221, 'Timberline Air', 'TMR', 'Canada', 'N'),
(222, 'TRAM', 'TMQ', 'Mauritania', 'N'),
(223, 'Tamir Airways', 'TMI', 'Israel', 'N'),
(224, 'Taxis Turisticos Marakame', 'TMH', 'Mexico', 'N'),
(225, 'Top-Fly', 'TLY', 'Spain', 'N'),
(226, 'TLC Air', 'TLS', 'United States', 'N'),
(227, 'Tunisavia', 'TAJ', 'Tunisia', 'N'),
(228, 'Eagle Canyon Airlines', 'TLO', 'United States', 'N'),
(229, 'Trans Atlantic Airlines', 'TLL', 'Sierra Leone', 'N'),
(230, 'Transport Africa', 'TLF', 'Sierra Leone', 'N'),
(231, 'Tikal Jets Airlines', 'TKC', 'Guatemala', 'N'),
(232, 'Tajikair', 'TJK', 'Tajikistan', 'N'),
(233, 'Travel International Air Charters', 'TIC', 'Zambia', 'N'),
(234, 'Toumai Air Tchad', 'THE', 'Chad', 'N'),
(235, 'Tar Heel Aviation', 'THC', 'United States', 'N'),
(236, 'Transport Canada', 'TGO', 'Canada', 'N'),
(237, 'Transportes Aereos Regionales', 'TGI', 'Mexico', 'N'),
(238, 'Trabajos Aereos', 'TGE', 'Spain', 'N'),
(239, 'TG Aviation', 'TGC', 'United Kingdom', 'N'),
(240, 'Transafrik International', 'TFK', 'Sao Tome and Principe', 'N'),
(241, 'Transport Facilitators', 'TFI', 'United States', 'N'),
(242, 'Thai Flying Helicopter Service', 'TFH', 'Thailand', 'N'),
(243, 'Trabajos Aereos Murcianos', 'AIM', 'Spain', 'N'),
(244, 'Telford Aviation', 'TEL', 'United States', 'N'),
(245, 'Tecnicas Fotograficas', 'TEF', 'Spain', 'N'),
(246, 'Tenir Airlines', 'TEB', 'Kyrgyzstan', 'N'),
(247, 'Tradewinds Airlines', 'TDX', 'United States', 'N'),
(248, 'Tadair', 'TDC', 'Spain', 'N'),
(249, 'Transcontinental Sur', 'TCT', 'Uruguay', 'N'),
(250, 'Trans Continental Airlines', 'TCN', 'United States', 'N'),
(251, 'Teledyne Continental Motors', 'TCM', 'United States', 'N'),
(252, 'Trans Continental Airlines', 'TCC', 'Sudan', 'N'),
(253, 'Tobago Express', 'TBX', 'Trinidad and Tobago', 'N'),
(254, 'Taban Air Lines', 'TBM', 'Iran', 'N'),
(255, 'TAB Express International', 'TBI', 'United States', 'N'),
(256, 'Trinity Air Bahamas', 'TBH', 'Bahamas', 'N'),
(257, 'Transbrasil', 'TBA', 'Brazil', 'N'),
(258, 'Travelair', 'TAX', 'Germany', 'N'),
(259, 'Transaustralian Air Express', 'AUC', 'Australia', 'N'),
(260, 'TAG Aviation USA', 'TAG', 'United States', 'N'),
(261, 'Tranporte Aereo Dominicano', 'TAD', 'Dominican Republic', 'N'),
(262, 'Trans Jet Airways', 'SWL', 'Sweden', 'N'),
(263, 'Skyplan Services', 'XXS', 'Canada', 'N'),
(264, 'Sector Airlines', 'XTR', 'Canada', 'N'),
(265, 'Stephenville Aviation Services', 'XSN', 'Canada', 'N'),
(266, 'Spectrum Air Service', 'XSA', 'United States', 'N'),
(267, 'SENEAM', 'XMX', 'Mexico', 'N'),
(268, 'Safarilink Aviation', 'XLK', 'Kenya', 'N'),
(269, 'Sirvair', 'VRS', 'Mexico', 'N'),
(270, 'Stichting Vliegschool 16Hoven', 'VGS', 'Netherlands', 'N'),
(271, 'Servicios Aereos Avandaro', 'VDO', 'Mexico', 'N'),
(272, 'Samarkand Airways', 'UZS', 'Uzbekistan', 'N'),
(273, 'Skif-Air', 'USK', 'Ukraine', 'N'),
(274, 'Servicios Aereos Universitarios', 'UNT', 'Mexico', 'N'),
(275, 'Second Sverdlovsk Air Enterprise', 'UKU', 'Russia', 'N'),
(276, 'S C Ion Tiriac', 'TIH', 'Romania', 'N'),
(277, 'South Pacific Island Airways', 'SPI', 'United States', 'Y'),
(278, 'Southern Airways', 'SOU', 'United States', 'Y'),
(279, 'Sonair Servico Aereo', 'SOR', 'Angola', 'N'),
(280, 'Solinair', 'SOP', 'Slovenia', 'N'),
(281, 'Sunshine Air Tours', 'SON', 'United States', 'N'),
(282, 'Southern Ohio Aviation Sales', 'SOH', 'United States', 'N'),
(283, 'Southern Cargo Air Lines', 'SOC', 'Russia', 'N'),
(284, 'Sun West Airlines', 'SNW', 'United States', 'N'),
(285, 'Sun Pacific International', 'SNP', 'United States', 'N'),
(286, 'Servizi Aerei', 'SNM', 'Italy', 'N'),
(287, 'Soonair Lines', 'SNL', 'United States', 'N'),
(288, 'Savanah Airlines', 'SNI', 'Nigeria', 'N'),
(289, 'Shans Air', 'SNF', 'Russia', 'N'),
(290, 'Skyline', 'SMT', 'Nigeria', 'N'),
(291, 'Samar Air', 'SMQ', 'Tajikistan', 'N'),
(292, 'Smalandsflyg', 'SMF', 'Sweden', 'N'),
(293, 'Servicios Aereos La Marquesa', 'SMD', 'Mexico', 'N'),
(294, 'Sabang Merauke Raya Air Charter', 'SMC', 'Indonesia', 'N'),
(295, 'Super Luza', 'SLZ', 'Angola', 'N'),
(296, 'Sete Linhas Aereas', 'SLX', 'Brazil', 'N'),
(297, 'Servicios Aereos Slainte', 'SLS', 'Mexico', 'N'),
(298, 'Salpa Aviation', 'SLP', 'Sudan', 'N'),
(299, 'Servicios Aereos de Los Angeles', 'AGE', 'Mexico', 'N'),
(300, 'Streamline', 'SLE', 'South Africa', 'N'),
(301, 'Sakaviaservice', 'AZG', 'Georgia', 'N'),
(302, 'Sky Harbor Air Service', 'SKD', 'United States', 'N'),
(303, 'Servicios De Rampa Y Mostrador', 'RMP', 'Mexico', 'N'),
(304, 'Servicios Aereos Profesionales', 'PSV', 'Dominican Republic', 'N'),
(305, 'Survey Udara (Penas)', 'PNS', 'Indonesia', 'N'),
(306, 'Servicios Aereos Premier', 'PMR', 'Mexico', 'N'),
(307, 'Servicios Intergrales De Aviacion', 'NTG', 'Mexico', 'N'),
(308, 'Servicios Aereos Del Norte', 'NTB', 'Mexico', 'N'),
(309, 'Servicio De Viglancia Aerea Del Ministerio De Seguridad Publica', 'MSP', 'Costa Rica', 'N'),
(310, 'Servico Aereo Regional', 'MSG', 'Mozambique', 'N'),
(311, 'SANSA', 'LRS', 'Costa Rica', 'N'),
(312, 'Sky Limo Corporation', 'LMO', 'United States', 'N'),
(313, 'Servicios Aereos Ejecutivos De La Laguna', 'LGU', 'Mexico', 'N'),
(314, 'Salem', 'KKS', 'Kazakhstan', 'N'),
(315, 'Sark International Airways', 'JIM', 'United Kingdom', 'N'),
(316, 'Saha Airlines Services', 'IRZ', 'Iran', 'N'),
(317, 'Svenska Direktflyg', 'HSV', 'Sweden', 'N'),
(318, 'Servicios Ejecutivos Gosa', 'HJE', 'Mexico', 'N'),
(319, 'Star XL German Airlines', 'GXL', 'Germany', 'N'),
(320, 'Sky Wings Airlines', 'GSW', 'Greece', 'N'),
(321, 'S.P. Aviation', 'GDG', 'United States', 'N'),
(322, 'South Coast Aviation', 'GAD', 'United Kingdom', 'N'),
(323, 'Sky Bus', 'FLH', 'United States', 'N'),
(324, 'Shalom Air Services', 'FFH', 'Nigeria', 'N'),
(325, 'Skypower Express Airways', 'EAN', 'Nigeria', 'N'),
(326, 'Sioux Falls Aviation', 'DKT', 'United States', 'N'),
(327, 'Shuangyang General Aviation', 'CSY', 'China', 'N'),
(328, 'Sunwest Home Aviation', 'CNK', 'Canada', 'N'),
(329, 'Swedish Airlines', 'CFL', 'Sweden', 'N'),
(330, 'Spectrem Air', 'CDS', 'South Africa', 'N'),
(331, 'Starair', 'BLY', 'Ireland', 'N'),
(332, 'Slate Falls Airways', 'SYJ', 'Canada', 'N'),
(333, 'Skyways', 'SYA', 'Argentina', 'N'),
(334, 'Safari Express Cargo', 'SXY', 'Kenya', 'N'),
(335, 'Sky Exec Aviation Services', 'SXC', 'Nigeria', 'N'),
(336, 'Southern Cross Aviation', 'SXA', 'United States', 'N'),
(337, 'Sky Jet', 'SWY', 'Switzerland', 'N'),
(338, 'Swazi Express Airways', 'SWX', 'Swaziland', 'N'),
(339, 'Sunwest Aviation (Lindquist Investment)', 'SWS', 'United States', 'N'),
(340, 'Swift Air (Interstate Equipment Leasing)', 'SWQ', 'United States', 'N'),
(341, 'Surninam International Victory Airline', 'SWO', 'Suriname', 'N'),
(342, 'Swedeways', 'SWE', 'Sweden', 'N'),
(343, 'South West Air', 'SWC', 'Canada', 'N'),
(344, 'Sevastopol-Avia', 'SVL', 'Ukraine', 'N'),
(345, 'Servicios De Transporte Aereo', 'SVI', 'Mexico', 'N'),
(346, 'Sundance Air', 'SUV', 'Venezuela', 'N'),
(347, 'Swiss Air Force', 'SUI', 'Switzerland', 'N'),
(348, 'Suburban Air Freight', 'SUB', 'United States', 'N'),
(349, 'Silesia Air', 'SUA', 'Czech Republic', 'N'),
(350, 'Styrian Airways', 'STY', 'Austria', 'N'),
(351, 'Star Air', 'STQ', 'Indonesia', 'N'),
(352, 'Sella Aviation', 'STJ', 'Netherlands', 'N'),
(353, 'Stadium City Limited', 'STC', 'United Kingdom', 'N'),
(354, 'Star Aviation', 'STA', 'United Kingdom', 'N'),
(355, 'Starspeed', 'SSP', 'United Kingdom', 'N'),
(356, 'Special Scope Limited', 'SSO', 'United Kingdom', 'N'),
(357, 'Slovak Government Flying Service', 'SSG', 'Slovakia', 'N'),
(358, 'Severstal', 'SSF', 'Russia', 'N'),
(359, 'Servicios Aereos Sunset', 'SSE', 'Mexico', 'N'),
(360, 'Star Up', 'SRU', 'Peru', 'N'),
(361, 'Selkirk Remote Sensing', 'SRS', 'Canada', 'N'),
(362, 'Servicios Aeronauticos Aero Personal', 'SRL', 'Mexico', 'N'),
(363, 'Searca', 'SRC', 'Colombia', 'N'),
(364, 'Servicos De Alquiler', 'SQL', 'Mexico', 'N'),
(365, 'Slovak Air Force', 'SQF', 'Slovakia', 'N'),
(366, 'Southeast Airmotive', 'SPU', 'United States', 'N'),
(367, 'Saber Airlines', 'SIS', 'Egypt', 'N'),
(368, 'Salair', 'SIR', 'United States', 'N'),
(369, 'Seco International', 'SIJ', 'Japan', 'N'),
(370, 'Sky Airlines', 'SHY', 'Turkey', 'N'),
(371, 'Shawnee Airline', 'SHW', 'United States', 'N'),
(372, 'Shooter Air Courier', 'SHR', 'Canada', 'N'),
(373, 'Sheremetyevo-Cargo', 'SHO', 'Russia', 'N'),
(374, 'Samson Aviation', 'SHL', 'United Kingdom', 'N'),
(375, 'STAC Swiss Government Flights', 'SGF', 'Switzerland', 'N'),
(376, 'Sky Gate International Aviation', 'SGD', 'Kyrgyzstan', 'N'),
(377, 'Southern Right Air Charter', 'SGC', 'South Africa', 'N'),
(378, 'Solent Flight', 'SFU', 'United Kingdom', 'N'),
(379, 'Skyfreight', 'SFT', 'United States', 'N'),
(380, 'Safe Air', 'SFP', 'Pakistan', 'N'),
(381, 'Sun Freight Logistics', 'SFG', 'Thailand', 'N'),
(382, 'Servicio Aereo Saltillo', 'SES', 'Mexico', 'N'),
(383, 'Selcon Airlines', 'SEO', 'Nigeria', 'N'),
(384, 'Sentel Corporation', 'SEL', 'United States', 'N'),
(385, 'Skyjet', 'SEK', 'Kazakhstan', 'N'),
(386, 'Shaheen Air Cargo', 'SEE', 'Pakistan', 'N'),
(387, 'Sedona Air Center', 'SED', 'United States', 'N'),
(388, 'Servicios Aereos Luce', 'SEB', 'Mexico', 'N'),
(389, 'Servicio Tecnico Aero De Mexico', 'SDX', 'Mexico', 'N'),
(390, 'Sud Airlines', 'SDU', 'France', 'N'),
(391, 'Spirit of Africa Airlines', 'SDN', 'Sudan', 'N'),
(392, 'Skydrift', 'SDL', 'United Kingdom', 'N'),
(393, 'SADELCA - Sociedad Aerea Del Caqueta', 'SDK', 'Colombia', 'N'),
(394, 'Sundorph Aeronautical Corporation', 'SDF', 'United States', 'N'),
(395, 'Skymaster Air Taxi', 'SDD', 'United States', 'N'),
(396, 'South African Non Scheduled Airways', 'SCS', 'South Africa', 'N'),
(397, 'Sunbird Airlines', 'CDL', 'United States', 'N'),
(398, 'Servicios Aereos de Chihuahua Aerochisa', 'AHI', 'Mexico', 'N'),
(399, 'Servicios Aereos San Cristobal', 'SCI', 'Mexico', 'N'),
(400, 'Socofer', 'SCF', 'Angola', 'N'),
(401, 'Seacoast Airlines', 'SCC', 'United States', 'N'),
(402, 'South Central Air', 'SCA', 'United States', 'N'),
(403, 'Spanish Air Force', 'AME', 'Spain', 'N'),
(404, 'Saint Barth Commuter', 'SBU', 'France', 'N'),
(405, 'Sky Bahamas', 'SBM', 'Bahamas', 'N'),
(406, 'Seven Bar Flying Service', 'SBF', 'United States', 'N'),
(407, 'STA-MALI', 'SBA', 'Mali', 'N'),
(408, 'Swiss Air-Ambulance', 'SAZ', 'Switzerland', 'N'),
(409, 'Sham Wing Airlines', 'SAW', 'Syrian Arab Republic', 'N'),
(410, 'Samal Air', 'SAV', 'Kazakhstan', 'N'),
(411, 'Secretaria de Marina', 'ANX', 'Mexico', 'N'),
(412, 'Sahel Aviation Service', 'SAO', 'Mali', 'N'),
(413, 'Servicios Aereos Nacionales', 'SAN', 'Ecuador', 'N'),
(414, 'SAM Colombia', 'SAM', 'Colombia', 'N'),
(415, 'Red Arrows Display Squadron', 'SAK', 'United Kingdom', 'N'),
(416, 'SASCO Airlines', 'SAC', 'Sudan', 'N'),
(417, 'State Air Company Berkut', 'BEC', 'Kazakhstan', 'N'),
(418, 'Rynes Aviation', 'RAA', 'United States', 'N'),
(419, 'Rwanda Airlines', 'RUA', 'Rwanda', 'N'),
(420, 'Rutland Aviation', 'RND', 'United Kingdom', 'N'),
(421, 'Rutas Aereas', 'RUC', 'Venezuela', 'N'),
(422, 'Rusline', 'RLU', 'Russia', 'Y'),
(423, 'Rubystar', 'RSB', 'Belarus', 'N'),
(424, 'Royal Phnom Penh Airways', 'PPW', 'Cambodia', 'Y'),
(425, 'Royal Oman Police', 'ROP', 'Oman', 'N'),
(426, 'Royal Daisy Airlines', 'KDR', 'Uganda', 'N'),
(427, 'Royal Bahrain Airlines', 'RYB', 'Bahrain', 'N'),
(428, 'Royal Aviation Express', 'RXP', 'Canada', 'N'),
(429, 'Royal American Airways', 'RLM', 'United States', 'N'),
(430, 'Royal Air Force', 'RRF', 'United Kingdom', 'N'),
(431, 'Royal Air Force', 'RRR', 'United Kingdom', 'N'),
(432, 'Rover Airways International', 'ROV', 'United States', 'N'),
(433, 'Rotormotion', 'RKT', 'United Kingdom', 'N'),
(434, 'Rossair', 'RSS', 'South Africa', 'N'),
(435, 'Roraima Airways', 'ROR', 'Guyana', 'N'),
(436, 'Rog-Air', 'FAD', 'Canada', 'N'),
(437, 'Rivne Universal Avia', 'UNR', 'Ukraine', 'N'),
(438, 'River Ministries Air Charter', 'RVM', 'South Africa', 'N'),
(439, 'Rikspolisstyrelsen', 'POL', 'Sweden', 'N'),
(440, 'Ridder Avia', 'RID', 'Kazakhstan', 'N'),
(441, 'Rick Lucas Helicopters', 'HPR', 'New Zealand', 'N'),
(442, 'Richland Aviation', 'RCA', 'United States', 'N'),
(443, 'Richardson\'s Airway', 'RIC', 'United States', 'N'),
(444, 'Richards Aviation', 'RVC', 'United States', 'N'),
(445, 'Riau Airlines', 'RIU', 'Indonesia', 'N'),
(446, 'Renown Aviation', 'RGS', 'United States', 'N'),
(447, 'Renan', 'RAN', 'Moldova', 'N'),
(448, 'Regional Air Express', 'REW', 'Germany', 'N'),
(449, 'Regional Air', 'RIL', 'Mauritania', 'N'),
(450, 'Reef Air', 'REF', 'New Zealand', 'N'),
(451, 'Reed Aviation', 'RAV', 'United Kingdom', 'N'),
(452, 'Red Sea Aviation', 'RDV', 'Egypt', 'N'),
(453, 'Real Aeroclub De Ternerife', 'RCD', 'Spain', 'N'),
(454, 'Raytheon Aircraft Company', 'RTN', 'United States', 'N'),
(455, 'Raya Jet', 'RYT', 'Jordan', 'N'),
(456, 'Ray Aviation', 'REI', 'Israel', 'N'),
(457, 'Raven Air', 'RVN', 'United States', 'N'),
(458, 'Raven Air', 'RVR', 'United Kingdom', 'N'),
(459, 'Rangemile Limited', 'RGM', 'United Kingdom', 'N'),
(460, 'Ram Aircraft Corporation', 'RMT', 'United States', 'N'),
(461, 'Race Cargo Airlines', 'ACE', 'Ghana', 'N'),
(462, 'Waddington FTU', 'WAD', 'United Kingdom', 'N'),
(463, 'RAF Valley SAR Training Unit', 'VLL', 'United Kingdom', 'N'),
(464, 'RAF St Athan', 'STN', 'United Kingdom', 'N'),
(465, 'Northwood Headquarters', 'NWO', 'United Kingdom', 'N'),
(466, 'Marham Flying Training Unit', 'MRH', 'United Kingdom', 'N'),
(467, 'Lossiemouth Flying Training Unit', 'LOS', 'United Kingdom', 'N'),
(468, 'RAF Leuchars', 'LCS', 'United Kingdom', 'N'),
(469, 'Leeming Flying Training Unit', 'LEE', 'United Kingdom', 'N'),
(470, 'Cranwell Flying Training Unit', 'CWL', 'United Kingdom', 'N'),
(471, 'Coningsby Flying Training Unit', 'CBY', 'United Kingdom', 'N'),
(472, 'Church Fenton Flying Training Unit', 'CFN', 'United Kingdom', 'N'),
(473, 'Quisqueya Airlines', 'QAS', 'Haiti', 'N'),
(474, 'Quick Air Jet Charter', 'QAJ', 'Germany', 'N'),
(475, 'Quest Diagnostics', 'LBQ', 'United States', 'N'),
(476, 'Quebec Government Air Service', 'QUE', 'Canada', 'N'),
(477, 'Quantex Environmental', 'QTX', 'Canada', 'N'),
(478, 'Qatar Amiri Flight', 'QAF', 'Qatar', 'N'),
(479, 'Qatar Air Cargo', 'QAC', 'Qatar', 'N'),
(480, 'Qanot Sharq', 'QNT', 'Uzbekistan', 'N'),
(481, 'Pyramid Air Lines', 'PYR', 'Egypt', 'N'),
(482, 'Puntavia Air Services', 'PTV', 'Djibouti', 'N'),
(483, 'Puma Linhas Aereas', 'PLY', 'Brazil', 'N'),
(484, 'Ptarmigan Airways', 'PTA', 'Canada', 'N'),
(485, 'Promotora Industria Totolapa', 'PTT', 'Mexico', 'N'),
(486, 'Professione VOlare', 'PVL', 'Italy', 'N'),
(487, 'Professional Express Courier Service', 'PAD', 'United States', 'N'),
(488, 'Pro Air Service', 'PSZ', 'United States', 'N'),
(489, 'Pro Air', 'PRH', 'United States', 'N'),
(490, 'Privilege Style L', 'PVG', 'Spain', 'N'),
(491, 'Private Jet Management', 'PJA', 'United States', 'N'),
(492, 'Priority Aviation Company', 'BCK', 'United States', 'N'),
(493, 'Princely Jets', 'PJP', 'Pakistan', 'N'),
(494, 'Lynx Aviation', 'SSX', 'United States', 'N'),
(495, 'GX Airlines', 'CBG', 'China', 'Y'),
(496, 'Tianjin Airlines', 'GCR', 'China', 'N'),
(497, 'Cathay Pacific', 'CPA', 'Hong Kong', 'Y'),
(498, 'Continental Airlines', 'COA', 'United States', 'Y'),
(499, 'Orbest', 'OBS', 'Portugal', 'Y'),
(500, 'Mauritania Airways', 'MTW', 'Mauritania', 'Y'),
(501, 'Transportes Aereos Cielos Andinos', 'NDN', 'Peru', 'Y'),
(502, 'Transportes Aereos de Ixtlan', 'TDI', 'Mexico', 'N'),
(503, 'Taxi Aereo Turistico', 'TUO', 'Mexico', 'N'),
(504, 'Tempelhof Airways', 'TEH', 'United States', 'N'),
(505, 'Tech-Mont Helicopter Company', 'TEM', 'Slovakia', 'N'),
(506, 'Sefofane Air Charters', 'SFE', 'South Africa', 'N'),
(507, 'Austrian Airlines', 'AUA', 'Austria', 'Y'),
(508, 'Turkish Airlines', 'THY', 'Turkey', 'Y'),
(509, 'Lufthansa', 'DLH', 'Germany', 'Y'),
(510, 'Egyptair', 'MSR', 'Egypt', 'Y'),
(511, 'Air Alsie', 'MMD', 'Denmark', 'Y');
COMMIT;
